services:
  - docker:dind

stages:
  - child-pipelines

# command-loop/.gitlab-ci.yml
command-loop:
  stage: child-pipelines
  variables:
    SERVICE_DIR: command-loop
  trigger:
    include: command-loop/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $SERVICE == "all"
    - if: $SERVICE == "command-loop"
    - changes:
        - command-loop/**/*

# minio_mc/.gitlab-ci.yml
minio_mc:
  stage: child-pipelines
  variables:
    SERVICE_DIR: minio_mc
  trigger:
    include: minio_mc/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $SERVICE == "all"
    - if: $SERVICE == "minio_mc"
    - changes:
        - minio_mc/**/*

# ansible/.gitlab-ci.yml
ansible:
  stage: child-pipelines
  variables:
    SERVICE_DIR: ansible
  trigger:
    include: ansible/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $SERVICE == "all"
    - if: $SERVICE == "ansible"
    - changes:
        - ansible/**/*

# terraform/.gitlab-ci.yml
terraform:
  stage: child-pipelines
  variables:
    SERVICE_DIR: terraform
  trigger:
    include: terraform/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $SERVICE == "all"
    - if: $SERVICE == "terraform"
    - changes:
        - terraform/**/*

# jawaws/.gitlab-ci.yml
jawaws:
  stage: child-pipelines
  variables:
    SERVICE_DIR: jawaws
  trigger:
    include: jawaws/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $SERVICE == "all"
    - if: $SERVICE == "jawaws"
    - changes:
        - jawaws/**/*

# platformio/.gitlab-ci.yml
platformio:
  stage: child-pipelines
  variables:
    SERVICE_DIR: platformio
  trigger:
    include: platformio/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $SERVICE == "all"
    - if: $SERVICE == "platformio"
    - changes:
        - platformio/**/*

# hive-hadoop-aws/.gitlab-ci.yml
hive-hadoop-aws:
  stage: child-pipelines
  variables:
    SERVICE_DIR: hive-hadoop-aws
  trigger:
    include: hive-hadoop-aws/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $SERVICE == "all"
    - if: $SERVICE == "hive-hadoop-aws"
    - changes:
        - hive-hadoop-aws/**/*

# system-utils/.gitlab-ci.yml
system-utils:
  stage: child-pipelines
  variables:
    SERVICE_DIR: system-utils
  trigger:
    include: system-utils/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $SERVICE == "all"
    - if: $SERVICE == "system-utils"
    - changes:
        - system-utils/**/*

# jupyter-iceberg/.gitlab-ci.yml
jupyter-iceberg:
  stage: child-pipelines
  variables:
    SERVICE_DIR: jupyter-iceberg
  trigger:
    include: jupyter-iceberg/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $SERVICE == "all"
    - if: $SERVICE == "jupyter-iceberg"
    - changes:
        - jupyter-iceberg/**/*

# esp-stack-trace-decoder/.gitlab-ci.yml
esp-stack-trace-decoder:
  stage: child-pipelines
  variables:
    SERVICE_DIR: esp-stack-trace-decoder
  trigger:
    include: esp-stack-trace-decoder/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $SERVICE == "all"
    - if: $SERVICE == "esp-stack-trace-decoder"
    - changes:
        - esp-stack-trace-decoder/**/*

# kubectl/.gitlab-ci.yml
kubectl:
  stage: child-pipelines
  variables:
    SERVICE_DIR: kubectl
  trigger:
    include: kubectl/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $SERVICE == "all"
    - if: $SERVICE == "kubectl"
    - changes:
        - kubectl/**/*

# htmlq/.gitlab-ci.yml
htmlq:
  stage: child-pipelines
  variables:
    SERVICE_DIR: htmlq
  trigger:
    include: htmlq/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $SERVICE == "all"
    - if: $SERVICE == "htmlq"
    - changes:
        - htmlq/**/*

# minio/.gitlab-ci.yml
minio:
  stage: child-pipelines
  variables:
    SERVICE_DIR: minio
  trigger:
    include: minio/.gitlab-ci.yml
    strategy: depend
  rules:
    - if: $SERVICE == "all"
    - if: $SERVICE == "minio"
    - changes:
        - minio/**/*

