FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN     apt-get update \
    &&  apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            iputils-ping \
            gnupg \
            apt-utils \
            rsync \
            git \
            make
